# Generated by example/leukaemia_network_pipeline.py -- the same experiment as the Python run.
# Usage (R >= 4.0, package FBNNet 2.0.1 installed):  Rscript reproduce_in_R.R
suppressMessages(library(FBNNet))

timeseries <- NULL
data("Leukeamia_Timeseries")          # list of 26 matrices (285 genes x 2-3 time points), already 0/1
timeseries <- Leukeamia_Timeseries
genes <- rownames(timeseries[[1]])
stopifnot(length(timeseries) == 26, length(genes) == 285)

maxK <- 2; temporal <- 1
cube <- constructFBNCube(target_genes = genes, conditional_genes = genes, timeseriesCube = timeseries,
                         maxK = maxK, temporal = temporal, useParallel = TRUE)

# 1) root level of the tree: conditional genes that survive the first level, per target
root <- do.call(rbind, lapply(names(cube), function(t) {
  g <- names(cube[[t]]$SubGenes)
  if (length(g) == 0) return(NULL)
  data.frame(target = t, conditional_gene = g, rank = seq_along(g), stringsAsFactors = FALSE)
}))
write.csv(root, "r_root_pool.csv", row.names = FALSE)

# 2) candidate rules before the per-gene cap
# (re-run with --dump-stage1 to also export the pre-cap candidate rules)
# 3) final network
network <- mineFBNNetwork(cube, genes, useParallel = FALSE,
                          threshold_confidence = 1, threshold_error = 0,
                          threshold_support = 1e-05, maxFBNRules = 5)
rows <- do.call(rbind, lapply(names(network$interactions), function(g) {
  ints <- network$interactions[[g]]
  if (length(ints) == 0) return(NULL)
  do.call(rbind, lapply(ints, function(r) data.frame(
    target = g, type = as.numeric(r$type), expression = as.character(r$expression), timestep = as.numeric(r$timestep),
    support = as.numeric(r$support), error = as.numeric(r$error), probability = as.numeric(r$probability),
    stringsAsFactors = FALSE)))
}))
write.csv(rows, "r_rules.csv", row.names = FALSE)
writeLines(capture.output(print(network)), "r_network.txt")
cat("R rules:", nrow(rows), " genes with rules:", length(unique(rows$target)), "\n")
print(sessionInfo())
